from tkinter import *
root=Tk()
root.geometry("400x400")
name=Label(root,text="NAME")
name.grid(row=1,column=0)
e1 = Entry(root).grid(row=3,column=1)
password=Label(root,text="PASSWORD")
password.grid(row=2,column=0)
e2 = Entry(root).grid(row=2,column=1)
root.mainloop()
